services:
  - type: web
    name: al-madina-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: al-madina-redis
          property: connectionString

  - type: keyvalue
    name: al-madina-redis
    plan: free
    ipAllowList: []
