/**
 * Machine-readable error codes returned in the `code` field of error responses.
 * The frontend switches on these rather than human-readable messages.
 */
export const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  RATE_LIMITED: 'RATE_LIMITED',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  // Products
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',

  // Categories / Collections
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',

  // Wishlist
  ALREADY_IN_WISHLIST: 'ALREADY_IN_WISHLIST',
  NOT_IN_WISHLIST: 'NOT_IN_WISHLIST',

  // Orders
  CART_EMPTY: 'CART_EMPTY',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  // Reviews
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Upload
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Coupons
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_CODE_TAKEN: 'COUPON_CODE_TAKEN',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_INACTIVE: 'COUPON_INACTIVE',
  COUPON_USAGE_LIMIT_REACHED: 'COUPON_USAGE_LIMIT_REACHED',
  COUPON_MIN_PURCHASE_NOT_MET: 'COUPON_MIN_PURCHASE_NOT_MET',

  // Roles / Permissions
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NAME_TAKEN: 'ROLE_NAME_TAKEN',
  ROLE_IS_SYSTEM: 'ROLE_IS_SYSTEM',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',

  // Tags
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_NAME_TAKEN: 'TAG_NAME_TAKEN',

  // Addresses
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',

  // Payments
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  PAYMENT_ALREADY_SETTLED: 'PAYMENT_ALREADY_SETTLED',
  PAYMENT_RETRY_NOT_ALLOWED: 'PAYMENT_RETRY_NOT_ALLOWED',
  PAYMENT_NOT_REFUNDABLE: 'PAYMENT_NOT_REFUNDABLE',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
